//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKER
    {
        public int NUMOUVR { get; set; }
        public int NUMDEP { get; set; }
        public Nullable<int> QTESTOCK { get; set; }
    
        public virtual DEPOT DEPOT { get; set; }
        public virtual OUVRAGE OUVRAGE { get; set; }
    }
}
