//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string email { get; set; }
        public string nom { get; set; }
        public string password { get; set; }
        public string hash { get; set; }
        public Nullable<System.DateTime> dateExpiration { get; set; }
        public Nullable<bool> valide { get; set; }
    }
}
